dist: trusty
sudo: true
git:
  depth: false
language: python
matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      language: generic
      addons:
        sonarcloud:
          organization: lucacappelletti94-github
          token:
            secure: h4w0/ZpqloC9g9MJ5J7p/GqOUuxueO1ydfLJKmzzYAT2wH6RNIpipFsJQ+7+nEk7SApztJE3DrV6FLI9BZxDcqaDYrxAuOOiIuKFewq+aJkKTxI4zXbt2h1CoDT5CReJ93EvoSfJXlxwLGnPhUdSfFvDyzRzBZe1cjPuhEzPEX3NwFS1e5a3BloaOYwQ6kM2fWzUb1xpxII3GdY0mUE6zaquUqdPh/XfJEls3c6FdKmYnQmU4ml4Cq2nknFcPLUyuiAQ7Cfa+kI+2Wlg/1mxchQ45g+VCi7bfTJfRPAKc/DOnxZynBKr+KCo8HG7rlkkasDPG0wlwzUPDKrDb2J+D5W7FKjys5Vs/3LaOY/7jlCtkuIunld8H2gVcaE/CMODWDY8NGbSlzPSS+/SXU/Brc+SohziPd/zuyBlZo8ZuZRY5hMRu3ANYhEarJh0YfxiswQQDGktOf1YHBCyUaPRGGZfJxaAg7I3PU9aX6V8yGdwc7iPQpDyxaIM8nBjZTlhtW9oDSa/XTxfT/2bwFcHryLgdFlJwTOqdQOX0YiJn88I4P/KXlNeyyIVKzye/OTXskdrf6vhYDmUAQXfE/8hvzFuhXT28p56V2gYBHZ7TaM4xih7Or6cSQGyu4w4bplUeA0KqgNNyfuq3B64UDii9pn+crUDcFhXtn93qUCURcc=
      env:
        - TRAVIS_PYTHON_VERSION=3.6.1
        - OPTIONAL_DEPS=1
before_install:
  # prepare the system to install prerequisites or dependencies
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      git clone https://github.com/matthew-brett/multibuild;
      source multibuild/osx_utils.sh;
      get_macpython_environment $TRAVIS_PYTHON_VERSION venv;
    fi
  - pip install --upgrade pytest
  - pip install pyobjc
install:
- pip install .[test]
before_script:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter;
    else
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter;
    fi  
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
script:
- rm -rf .coverage
- coverage erase
- pytest --cov=keras_ding --cov-report xml:coverage.xml
- coverage combine --append || true
- coverage report
- coverage xml
- sonar-scanner
after_success:
- coveralls
- python-codacy-coverage -r coverage.xml
env:
  global:
  - secure: NsM5U/BSYvLOfKsa95wo4X+MLvvknKblcH072D/0vyCh+xwvdxxZtTTtRH4L+BlSSAg5PDVbxV6+KiUV0t7myNXDUugmeoVSQjIu5V1B0BhRh/1LoIuJD30ojW20d2GkQrLhIWfBxCFyc7QM6GJAAaTC/bA3sDYzmRJXEQZMuz1S+bmuW/UK8Mg2F76tLevqQka030QLQU/rrpb4EnKTbwm8pvHTZYOhfpx5SB4zw6nyPeopN/AozO5vdyIPDSwCaYwQHjrzi4SIqOlA4ObNNUajNj2r8RmYSjt3X+PevP47pncTrXPKiqL5d9agkf0p5o1Fz9cmAZ158umc0gg+Q6XHrNDqmizmRSxtD1ujUKaBaeMIe3yOOK9s8/c3uIsje+sPertu18hj6LWrBNHFd7kAOV+/pXPCanTvD+ckbwIk20ymDQR1EsZWs2bC9vPIsAbkR5KvgJk2H3wAzNf2s6JfN5tj3ayDAqrZFFMUBlO8c7EUV0NWnhqAWisTpbo2Vo8YTx9jxj1QP2OWtrPh+7NAKB7AUlzqQIa4s7+o2PYq/643mmZmMNvxyFEaSac8++ZO/fg/dP/0QI6HPOe8bqicakmLOKQH8hw7VaFN6gxUdcjOKaQjkR/qV/EA15N0dSNB3zk8CxukR2nVlC1Ctf4OdPl9SUdKWK87ijPMjUo=
  - secure: prIL+yam6GhYeiyaMweOvZGjdQ62fxIWOatOqPfHYYsRkIE0AaxSXfLW4Q+/K4tqNU7YMRMovEyqmZHkK8FnuXcuatxGJNLkRruxhxV+7mfgCIem5WEBev5rYouhBfbVqeU2LjJF9H/NidUfisbt3Tm1OG2IglMv8VAg+pTDDmTwN0uZi1Pi4Vn3GYkZ5HnxX9/D2Re0U8iXW7wP5M34w3i7FEOIGvhcJDBTO0JHOr81tZigfgno7QkIU+xy/lBiJlWZ7K31xaWf3lx89UXVOfkHPxgtJQqa8RRqJ70pMCTWncD4XoVmJnaTXyjLp8roBLk0SS9oVLOGGsyHEia9kmDgabJMUjrUsZc+cw4CQ2uBmOzZc1mQG+aTRZXin0naTuRHiNvNrkw+TUVS9SFadK90sBQcyWGF9aKO0YFUWQ6wCp1rP7SNiQxmmqB7DUzsaH1yEndOD+BNznvYzdkGme9UzGZkGjTHBpG1IZTpUyKBPxMQdAqtvEv+lftOEmrA/+R9X96vbu2NoTZft2YzNKb9DDe0xcnNX4LCktHZO7Vj7KNXABdrytePvxVa1eEcU4RRzsXziYEpRz00d2DgSRcNOrU8mefR8iLSG2nvcbPGVyZ/HXeGMpiKFl6FWjyZ7FdO2eRA2wulPOPY00ZSG7qAS3JOGzKflL6/gFnB3No=
