dist: trusty
sudo: false
git:
  depth: false
addons:
  sonarcloud:
    organization: lucacappelletti94-github
    token:
      secure: adWbLgVLpV3DIFK4zBnzcaLL3tuJWr0QqEC42A3rmo6Bth6kwbaqh6KbuscaEDPZ4KXjuoAjRLliDFXJ90PbZ411fFVfQOPlE5nkhOBaXIgCOXx+bYRlV+8dNrysvKujqlz/zMiEAAWW5EipDLTYs7SXXZfOMUHVJOBj/MvupVssE/1GcjHnWbJXR25WIWZQiWgWbyxw4JgGUtFEj8SspZllJ1dCX2F3lSZA3IIbQn3T28wcOZu1r2vDugtJqDpudKAyOuxstsdwwNC9dLlt5sGOb8VV7PVNGWd/wil9pMLWGcJwBSG2p6zYBlCUjGBzRJVkq3m096E6kNrFYG5OSyMk/DOPzDzcoDo37APPg49dzye1328vQfxKSp81nY8d+iPkjjHts1/716gFDfBIz2Kc3eF6t4s1vEBn1M993X7fuuk8NbhMsyYgKH02lvMvt+hyztm5sSa0yGPdo4lMB2SUo4ZnHEWZXl8lCdeBqQIzFgJJdlDXrRuFUtmb/CmPnAPv2g9QeBqY9NyPnLAqD/XFYvw2vuRwr/oCrm2QkrD/iRL0pLpD7LwgIgGsShEoON4UccxdiDYwnE/40pnqird3z9M+8hs49Z4/s549iQ2Wt6aZAgOgebVYQeWRQm64lFjxj5OQ5qcINI1oCwMZA1vhO1D7gHw27aRssAkFTLQ=
  apt:
    update: true
    packages:
      - python3-dev
      - libasound2-dev
language: python
python:
- '3.6'
before_install:
- pip install pip --upgrade
- pip uninstall -y numpy
- pip install numpy --upgrade
- pip install --upgrade pytest
- pip install tensorflow
install:
- pip install .[test]
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
script:
- rm -rf .coverage
- coverage erase
- export AUDIODEV=null
- pytest -vs --cov=keras_ding --cov-report xml:coverage.xml
- coverage combine --append || true
- coverage report
- coverage xml
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi
after_success:
- coveralls
- python-codacy-coverage -r coverage.xml
env:
  global:
  - secure: NsM5U/BSYvLOfKsa95wo4X+MLvvknKblcH072D/0vyCh+xwvdxxZtTTtRH4L+BlSSAg5PDVbxV6+KiUV0t7myNXDUugmeoVSQjIu5V1B0BhRh/1LoIuJD30ojW20d2GkQrLhIWfBxCFyc7QM6GJAAaTC/bA3sDYzmRJXEQZMuz1S+bmuW/UK8Mg2F76tLevqQka030QLQU/rrpb4EnKTbwm8pvHTZYOhfpx5SB4zw6nyPeopN/AozO5vdyIPDSwCaYwQHjrzi4SIqOlA4ObNNUajNj2r8RmYSjt3X+PevP47pncTrXPKiqL5d9agkf0p5o1Fz9cmAZ158umc0gg+Q6XHrNDqmizmRSxtD1ujUKaBaeMIe3yOOK9s8/c3uIsje+sPertu18hj6LWrBNHFd7kAOV+/pXPCanTvD+ckbwIk20ymDQR1EsZWs2bC9vPIsAbkR5KvgJk2H3wAzNf2s6JfN5tj3ayDAqrZFFMUBlO8c7EUV0NWnhqAWisTpbo2Vo8YTx9jxj1QP2OWtrPh+7NAKB7AUlzqQIa4s7+o2PYq/643mmZmMNvxyFEaSac8++ZO/fg/dP/0QI6HPOe8bqicakmLOKQH8hw7VaFN6gxUdcjOKaQjkR/qV/EA15N0dSNB3zk8CxukR2nVlC1Ctf4OdPl9SUdKWK87ijPMjUo=
  - secure: prIL+yam6GhYeiyaMweOvZGjdQ62fxIWOatOqPfHYYsRkIE0AaxSXfLW4Q+/K4tqNU7YMRMovEyqmZHkK8FnuXcuatxGJNLkRruxhxV+7mfgCIem5WEBev5rYouhBfbVqeU2LjJF9H/NidUfisbt3Tm1OG2IglMv8VAg+pTDDmTwN0uZi1Pi4Vn3GYkZ5HnxX9/D2Re0U8iXW7wP5M34w3i7FEOIGvhcJDBTO0JHOr81tZigfgno7QkIU+xy/lBiJlWZ7K31xaWf3lx89UXVOfkHPxgtJQqa8RRqJ70pMCTWncD4XoVmJnaTXyjLp8roBLk0SS9oVLOGGsyHEia9kmDgabJMUjrUsZc+cw4CQ2uBmOzZc1mQG+aTRZXin0naTuRHiNvNrkw+TUVS9SFadK90sBQcyWGF9aKO0YFUWQ6wCp1rP7SNiQxmmqB7DUzsaH1yEndOD+BNznvYzdkGme9UzGZkGjTHBpG1IZTpUyKBPxMQdAqtvEv+lftOEmrA/+R9X96vbu2NoTZft2YzNKb9DDe0xcnNX4LCktHZO7Vj7KNXABdrytePvxVa1eEcU4RRzsXziYEpRz00d2DgSRcNOrU8mefR8iLSG2nvcbPGVyZ/HXeGMpiKFl6FWjyZ7FdO2eRA2wulPOPY00ZSG7qAS3JOGzKflL6/gFnB3No=
